"""initial schema

Revision ID: 0b81e616d01b
Revises: 
Create Date: 2026-05-23 13:37:28.363574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b81e616d01b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('property_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_type_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('input_type', sa.Enum('boolean', 'select', 'number', name='inputtype'), nullable=False),
    sa.Column('options', sa.String(length=500), nullable=True),
    sa.Column('default_value', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['step_type_id'], ['step_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_property_id', sa.Integer(), nullable=False),
    sa.Column('trigger_value', sa.String(length=100), nullable=False),
    sa.Column('reveals_property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reveals_property_id'], ['property_definitions.id'], ),
    sa.ForeignKeyConstraint(['trigger_property_id'], ['property_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_definition_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('non_negative', 'min_value', 'max_value', 'required', 'one_of', 'integer_only', name='ruletype'), nullable=False),
    sa.Column('rule_value', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('step_type_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['step_type_id'], ['step_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_property_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_step_id', sa.Integer(), nullable=False),
    sa.Column('property_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['property_definition_id'], ['property_definitions.id'], ),
    sa.ForeignKeyConstraint(['recipe_step_id'], ['recipe_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_property_values')
    op.drop_table('recipe_steps')
    op.drop_table('property_validation_rules')
    op.drop_table('property_conditions')
    op.drop_table('recipes')
    op.drop_table('property_definitions')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_table('step_types')
    # ### end Alembic commands ###
